on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    
jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: r-lib/actions/setup-pandoc@v2
      
      - uses: r-lib/actions/setup-r@v2

      - run:
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "devtools"))'
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
