on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
    
permissions:
  contents: write

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
            
      - uses: r-lib/actions/setup-r@v2

      - run:
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr"))'
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          
      - name: Render slides
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: revealjs # If set, it will be equivalent to `quarto render --to html`
          path: slides/lec-1.qmd # By default, the current working dir is used i.e `quarto render .`

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
